### ISSUE TITLE
Clean up perl 5.24 warnings

### ISSUE THREAD

**Issue by dmcbride** [Kantigen/ka-server#1]
There are two phases here: put in the proper `use experimental ...` line to any file using smartmatch or given/when, and then to actually remove the smartmatch, given/when, possibly just replacing it with other modules that won't disappear on us at some point in the future during another perl upgrade.

**Comment by icydee** [comment]
I think we still have a few yo fix. Run the test 000_compile.t to find them all

**Comment by nataliethistime** [comment]
`000_compile.t` passed.

**Comment by icydee** [comment]
Really? Nice, could not check since i am sitting in a shopping centre on holiday 😀
